#!/usr/bin/env bash
# Attempt at a wrapper around boot2docker so everything is set up
# in an isolated session.
# NB: Errors from docker on ports/certificate may require a delete/init
# cycle to resolve

function error_exit {
  echo "$1" 1>&2
  exit 1
}

echo "WARNING: boot2docker is deprecated, use docker-machine instead" 1>&2

[[ `uname` == "Darwin" ]] || error_exit "b2d-session only runs on Mac"

# Start up...
b2d=$(command -v boot2docker) || error_exit "No boot2docker command found"

# Are we running already?
b2d_status=$($b2d status 2>/dev/null || echo "poweroff")

# Cycle VM, use at least 5GB of memory
if [ "$b2d_status" == "poweroff" ] ; then
  $b2d down
  $b2d delete
  $b2d init -m 5120
  $b2d up || error_exit "Could not start boot2docker VM"
fi

eval "$($b2d shellinit)"
bash -i
echo "Exiting boot2docker session"
$b2d down
exit $?
